title: Offersmom
description: >-
  Offersmom is coupons and deals site that sharing coupons, discounts and deals
  information about clothing, health, domain name, web hosting from many
  providers over the world at <a href="https://Offersmom.com/">Offersmom</a>
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
